training:
#  entropy_strength: 0.0003
  sync_each_n_games: 20
  learning_rate: 0.001
  actor_loss_weight: 0.1
  critic_loss_weight: 1.0
  use_data_augmentation: false
  logit_regularization_strength: 0.01
#  actor_label_smoothing: 0.01
model:
  rnn_units: [47, 53, 43]
  max_agents: 8
  use_visible_agents: true
  use_communication: false
  comm_units: [43]
  comm_type: state_avg_reader

maze_size: 3

reward:
  discount_rate: 0.95
  step_reward: 0.1
  exit_reward: 1.0
  exit_reward_diff_decay: 0.8
